### ISSUE TITLE
/api/config.php not writable

### ISSUE THREAD

**Issue by Askek23** [gamelaster/opensupports-docker#3] opened 2021-12-01 15:20 UTC
Hi, 

I tried to install the software as you mentioned but I recive the error intalling it. It says that /api/config is not writable. I've tried changing the mode of the folder to 777 but, it didn't worked.

Attach you a pic. 

Thank you!!

![failure](https://user-images.githubusercontent.com/60330894/144261545-46a2aa55-d64d-49b3-b7c1-0ea23dcaa670.png)

**Comment by klenzel** [comment] 2021-12-28 09:05
Try to open a console:

docker exec -it YOUR_CONTAINER bash

and then:

touch /config/config.php
chown www-data: /config/config.php

**Comment by gamelaster** [comment] 2021-12-28 16:12
I will try to fix it ASAP, also upgrade to latest version.

**Comment by Askek23** [comment] 2021-12-28 23:01
Finally its working!!

As @klenzel said, all I had to do is open a bash to the container and then change give write permissions over the file.

1) docker exec -it YOUR_CONTAINER bash
2) cd /var/www/html/api 
3) chmod 777 config.php

![imagen](https://user-images.githubusercontent.com/60330894/147613276-45ed10ac-cb65-4044-ab08-d77e19a0e8af.png)

Thanks and happy new year! :D

Alex.

**Comment by mtlimon** [comment] 2022-02-18 08:05
No luck with docker exec -it YOUR_CONTAINER bash

and then:

touch /config/config.php
chown www-data: /config/config.php

I get "touch: setting times of 'config.php': No such file or directory" exists? 

ls -l shows 
lrwxrwxrwx  1 root root    18 Feb 17 23:35 config.php -> /config/config.php

I also tried chmod 777 config.php but continue to get chmod: cannot operate on dangling symlink 'config.php' error

**Comment by Saplyng** [comment] 2022-12-13 20:32
I'm also getting this issue and am unable to chmod config.php getting the dangling symlink error. This was tried in a new ubuntu vm with docker freshly installed - if that helps at all.

**Comment by gamelaster** [comment] 2023-02-02 12:05
I can't reproduce this, it works just fine for me. :frowning_face: If anyone still have the issue, please add comment here. Until that, let's close the issue.

**Closed as completed** 2023-02-02 12:07 UTC
